// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/airtime-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/airtime-services">> = Specific
  const handler = {} as typeof import("../../../app/admin/airtime-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/api-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/api-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assets">> = Specific
  const handler = {} as typeof import("../../../app/admin/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/bvn/android-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bvn/android-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/bvn/android-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/bvn/modification-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bvn/modification-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/bvn/modification-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalog">> = Specific
  const handler = {} as typeof import("../../../app/admin/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/disputes">> = Specific
  const handler = {} as typeof import("../../../app/admin/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/kyc-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kyc-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/kyc-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../../app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/marketers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketers">> = Specific
  const handler = {} as typeof import("../../../app/admin/marketers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/nin/templates/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/nin/templates/builder">> = Specific
  const handler = {} as typeof import("../../../app/admin/nin/templates/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/nin/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/nin/templates">> = Specific
  const handler = {} as typeof import("../../../app/admin/nin/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../../app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../../app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pos-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pos-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/pos-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing">> = Specific
  const handler = {} as typeof import("../../../app/admin/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers">> = Specific
  const handler = {} as typeof import("../../../app/admin/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../../app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/notifications">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/software-development/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/software-development/all">> = Specific
  const handler = {} as typeof import("../../../app/admin/software-development/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/software-development/assigned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/software-development/assigned">> = Specific
  const handler = {} as typeof import("../../../app/admin/software-development/assigned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/software-development/completed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/software-development/completed">> = Specific
  const handler = {} as typeof import("../../../app/admin/software-development/completed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/software-development/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/software-development/finance">> = Specific
  const handler = {} as typeof import("../../../app/admin/software-development/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/software-development/in-progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/software-development/in-progress">> = Specific
  const handler = {} as typeof import("../../../app/admin/software-development/in-progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/training-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/training-manager">> = Specific
  const handler = {} as typeof import("../../../app/admin/training-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ui-metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ui-metrics">> = Specific
  const handler = {} as typeof import("../../../app/admin/ui-metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/disputes">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/kyc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/kyc">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/kyc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/kyc/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/kyc/pending">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/kyc/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/marketer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/marketer">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/marketer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/requests">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/2fa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/2fa">> = Specific
  const handler = {} as typeof import("../../../app/login/2fa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../../app/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/agency-banking/marketer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/agency-banking/marketer">> = Specific
  const handler = {} as typeof import("../../../app/services/agency-banking/marketer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/agency-banking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/agency-banking">> = Specific
  const handler = {} as typeof import("../../../app/services/agency-banking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/agency-banking/pos-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/agency-banking/pos-request">> = Specific
  const handler = {} as typeof import("../../../app/services/agency-banking/pos-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/airtime-2-cash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime/airtime-2-cash">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/airtime-2-cash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/glo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime/glo">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/glo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/mtn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime/mtn">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/mtn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/share-n-sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime/share-n-sell">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/share-n-sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/airtime/vtu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/airtime/vtu">> = Specific
  const handler = {} as typeof import("../../../app/services/airtime/vtu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bills/cable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bills/cable">> = Specific
  const handler = {} as typeof import("../../../app/services/bills/cable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bills/electricity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bills/electricity">> = Specific
  const handler = {} as typeof import("../../../app/services/bills/electricity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bills">> = Specific
  const handler = {} as typeof import("../../../app/services/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/android-license/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn/android-license">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/android-license/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/central-risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn/central-risk">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/central-risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/modification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn/modification">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/modification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/printout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn/printout">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/printout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/bvn/retrieval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/bvn/retrieval">> = Specific
  const handler = {} as typeof import("../../../app/services/bvn/retrieval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/certification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac/certification">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/certification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/jtb-tin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac/jtb-tin">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/jtb-tin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/post-incorporation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac/post-incorporation">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/post-incorporation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac/registration">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/cac/status-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/cac/status-report">> = Specific
  const handler = {} as typeof import("../../../app/services/cac/status-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/data/cooperate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/data/cooperate">> = Specific
  const handler = {} as typeof import("../../../app/services/data/cooperate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/data/gift/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/data/gift">> = Specific
  const handler = {} as typeof import("../../../app/services/data/gift/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/data/mtn-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/data/mtn-data">> = Specific
  const handler = {} as typeof import("../../../app/services/data/mtn-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/data">> = Specific
  const handler = {} as typeof import("../../../app/services/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/data/sme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/data/sme">> = Specific
  const handler = {} as typeof import("../../../app/services/data/sme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/jamb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/jamb">> = Specific
  const handler = {} as typeof import("../../../app/services/education/jamb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/nabteb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/nabteb">> = Specific
  const handler = {} as typeof import("../../../app/services/education/nabteb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/nbais/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/nbais">> = Specific
  const handler = {} as typeof import("../../../app/services/education/nbais/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/neco/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/neco">> = Specific
  const handler = {} as typeof import("../../../app/services/education/neco/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/nysc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/nysc">> = Specific
  const handler = {} as typeof import("../../../app/services/education/nysc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education">> = Specific
  const handler = {} as typeof import("../../../app/services/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/education/waec/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/education/waec">> = Specific
  const handler = {} as typeof import("../../../app/services/education/waec/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/ipe-clearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin/ipe-clearance">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/ipe-clearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/modification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin/modification">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/modification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/printout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin/printout">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/printout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/slip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin/slip">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/slip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/nin/validation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/nin/validation">> = Specific
  const handler = {} as typeof import("../../../app/services/nin/validation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/software-development/custom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/software-development/custom">> = Specific
  const handler = {} as typeof import("../../../app/services/software-development/custom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/software-development/mobile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/software-development/mobile">> = Specific
  const handler = {} as typeof import("../../../app/services/software-development/mobile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/software-development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/software-development">> = Specific
  const handler = {} as typeof import("../../../app/services/software-development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/software-development/web/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/software-development/web">> = Specific
  const handler = {} as typeof import("../../../app/services/software-development/web/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/agency-updates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/agency-updates">> = Specific
  const handler = {} as typeof import("../../../app/services/training/agency-updates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/bvn-modification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/bvn-modification">> = Specific
  const handler = {} as typeof import("../../../app/services/training/bvn-modification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/cac-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/cac-registration">> = Specific
  const handler = {} as typeof import("../../../app/services/training/cac-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/free-user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/free-user">> = Specific
  const handler = {} as typeof import("../../../app/services/training/free-user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/nin-modification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/nin-modification">> = Specific
  const handler = {} as typeof import("../../../app/services/training/nin-modification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training">> = Specific
  const handler = {} as typeof import("../../../app/services/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/training/premium-user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/training/premium-user">> = Specific
  const handler = {} as typeof import("../../../app/services/training/premium-user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/bvn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/bvn">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/bvn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/cac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/cac">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/cac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/driver-license/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/driver-license">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/driver-license/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/nin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/nin">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/nin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/passport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/passport">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/passport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/phone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/phone">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/phone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/plate-number/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/plate-number">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/plate-number/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/tin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/tin">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/tin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/verification/voters-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/verification/voters-card">> = Specific
  const handler = {} as typeof import("../../../app/services/verification/voters-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/user-dashboard/my-projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user-dashboard/my-projects">> = Specific
  const handler = {} as typeof import("../../../app/user-dashboard/my-projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/assets">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/catalog/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/catalog/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/catalog/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/catalog">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/disputes">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/finance/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/finance/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/kyc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kyc">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/kyc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/marketers/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketers/action">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/marketers/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/marketers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/marketers">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/marketers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/nin-templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/nin-templates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/nin-templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/nin-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/nin-templates">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/nin-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/pos/requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pos/requests/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/pos/requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/pos/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pos/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/pos/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pricing">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/providers/[id]/api-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]/api-key">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/providers/[id]/api-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/providers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/providers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/providers/[id]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]/test">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/providers/[id]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/providers/category/[category]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/category/[category]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/providers/category/[category]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/daily-profit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/daily-profit">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/daily-profit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/export">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/requests/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/requests/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/requests/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/service/logs/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/service/logs/[reference]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/service/logs/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/service/refund/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/service/refund/[reference]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/service/refund/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/service/retry/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/service/retry/[reference]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/service/retry/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/services/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services/availability">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/services/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/services/manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services/manual">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/services/manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/services/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/services/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/settings/security/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/security">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/settings/security/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/software/requests/[id]/costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/software/requests/[id]/costs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/software/requests/[id]/costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/software/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/software/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/software/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system-settings/bvn-android/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system-settings/bvn-android">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system-settings/bvn-android/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[id]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[id]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/wallet/adjust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wallet/adjust">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/wallet/adjust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/wallet/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wallet/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/wallet/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/2fa/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/2fa/check">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/2fa/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/2fa/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/2fa/setup">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/2fa/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/2fa/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/2fa/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/2fa/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/password-reset/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password-reset/request">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/password-reset/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/password-reset/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password-reset/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/password-reset/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/signup-otp/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup-otp/request">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/signup-otp/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/signup-otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup-otp/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/signup-otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disputes">> = Specific
  const handler = {} as typeof import("../../../app/api/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/status">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/kyc/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/kyc/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketers/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketers/me">> = Specific
  const handler = {} as typeof import("../../../app/api/marketers/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/marketers/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketers/register">> = Specific
  const handler = {} as typeof import("../../../app/api/marketers/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/password">> = Specific
  const handler = {} as typeof import("../../../app/api/me/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/pin">> = Specific
  const handler = {} as typeof import("../../../app/api/me/pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/me/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../../app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/popup-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/popup-messages">> = Specific
  const handler = {} as typeof import("../../../app/api/popup-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pricing/parameters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/parameters">> = Specific
  const handler = {} as typeof import("../../../app/api/pricing/parameters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing">> = Specific
  const handler = {} as typeof import("../../../app/api/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/service-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-catalog">> = Specific
  const handler = {} as typeof import("../../../app/api/service-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/service/[category]/[action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service/[category]/[action]">> = Specific
  const handler = {} as typeof import("../../../app/api/service/[category]/[action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/service/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service">> = Specific
  const handler = {} as typeof import("../../../app/api/service/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/service/status/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service/status/[reference]">> = Specific
  const handler = {} as typeof import("../../../app/api/service/status/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/service/webhook/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service/webhook/[reference]">> = Specific
  const handler = {} as typeof import("../../../app/api/service/webhook/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/software/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/software/requests">> = Specific
  const handler = {} as typeof import("../../../app/api/software/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/system/contact-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/contact-settings">> = Specific
  const handler = {} as typeof import("../../../app/api/system/contact-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/system/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/api/system/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/templates/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/templates/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/training/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training">> = Specific
  const handler = {} as typeof import("../../../app/api/training/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/training/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/training/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/transaction/[reference]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transaction/[reference]/status">> = Specific
  const handler = {} as typeof import("../../../app/api/transaction/[reference]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../../app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/transactions/recent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/transactions/recent">> = Specific
  const handler = {} as typeof import("../../../app/api/user/transactions/recent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification">> = Specific
  const handler = {} as typeof import("../../../app/api/verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/balance">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/fund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/fund">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/fund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/spend-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/spend-metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/spend-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/virtual-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/virtual-account">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/virtual-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/virtual-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/virtual-accounts">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/virtual-accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/webhook/monnify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/webhook/monnify">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/webhook/monnify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/webhook/paymentpoint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/webhook/paymentpoint">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/webhook/paymentpoint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/services/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
