var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/reports/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_2299993b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f00bdf5b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_b704424f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f148858._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2cd70997._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_c756e529._.js")
R.c("server/chunks/ssr/node_modules_next-auth_489f0482._.js")
R.c("server/chunks/ssr/node_modules_openid-client_5e2b25d2._.js")
R.c("server/chunks/ssr/node_modules_b20cc885._.js")
R.c("server/chunks/ssr/node_modules_@bufbuild_protobuf_dist_esm_45e8e06c._.js")
R.c("server/chunks/ssr/node_modules_@arcjet_protocol_d9b3d42e._.js")
R.c("server/chunks/ssr/a9bf9_@arcjet_analyze-wasm__virtual_arcjet_analyze_js_req_component_core_8188b45c.js")
R.c("server/chunks/ssr/node_modules_@arcjet_analyze-wasm__virtual_7ec6d64b._.js")
R.c("server/chunks/ssr/node_modules_@arcjet_analyze-wasm_01de8ee9._.js")
R.c("server/chunks/ssr/node_modules_@connectrpc_connect_dist_esm_e1569267._.js")
R.c("server/chunks/ssr/node_modules_undici_07b09707._.js")
R.c("server/chunks/ssr/node_modules_joi_d28837bf._.js")
R.c("server/chunks/ssr/node_modules_zod_57d88d32._.js")
R.c("server/chunks/ssr/node_modules_entities_lib_25c5c79a._.js")
R.c("server/chunks/ssr/node_modules_619dbede._.js")
R.c("server/chunks/ssr/[root-of-the-server]__87763c94._.js")
R.c("server/chunks/ssr/app_admin_reports_loading_tsx_12632249._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_reports_page_actions_a8d1615f.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/reports/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_0 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/app/admin/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/app/admin/reports/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/admin/reports/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/reports/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_0 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/app/admin/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/app/admin/reports/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/admin/reports/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
