"use client"

import type React from "react"

import { useState, useEffect } from "react"
import useDynamicPricing from "@/hooks/useDynamicPricing"
import { motion } from "framer-motion"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useToast } from "@/hooks/use-toast"
import { Download, GraduationCap, ShoppingCart } from "lucide-react"
import { PinPrompt } from "@/components/PinPrompt"
// Removed manual storage and direct API; unified via dynamic pricing + submitService
import jsPDF from "jspdf"

export default function WAECPage() {
  const [serviceType, setServiceType] = useState("")
  const [quantity, setQuantity] = useState(1)
  const [customQuantity, setCustomQuantity] = useState("")
  const [candidateName, setCandidateName] = useState("")
  const [servicePrice, setServicePrice] = useState(0)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showSuccess, setShowSuccess] = useState(false)
  const [referenceId, setReferenceId] = useState("")
  const [isPinPromptOpen, setIsPinPromptOpen] = useState(false)
  const [pendingPayload, setPendingPayload] = useState<any>(null)
  const { toast } = useToast()

  // Map UI label to variant slug
  const toSlugId = (label: string) => {
    const map: Record<string, string> = {
      "WAEC Pin": "waec-pin",
      "GCE Registration Pin": "gce-registration-pin",
    }
    const id = map[label] || label.toLowerCase().replace(/[^a-z0-9]+/g, ".")
    return id
  }

  // Dynamic pricing via hook; reflect per-unit price
  const { price: dynamicPrice, isLoading: dbLoading, error: pricingError, submitService } = useDynamicPricing(
    "education",
    "waec",
    serviceType ? toSlugId(serviceType) : ""
  )

  useEffect(() => {
    if (!serviceType || typeof dynamicPrice !== "number") {
      setServicePrice(0)
      return
    }
    setServicePrice(Number(dynamicPrice))
  }, [serviceType, dynamicPrice])

  const totalPrice = servicePrice * (quantity === 0 ? Number.parseInt(customQuantity) || 1 : quantity)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)

    const finalQuantity = quantity === 0 ? Number.parseInt(customQuantity) || 1 : quantity
    try {
      setPendingPayload({
        amount: totalPrice,
        eduType: serviceType,
        quantity: finalQuantity,
        candidateName,
      })
      setIsPinPromptOpen(true)
    } finally {
      setIsSubmitting(false)
    }
  }

  const handlePinConfirm = async (pin: string) => {
    setIsPinPromptOpen(false)
    setIsSubmitting(true)

    try {
      if (!serviceType) throw new Error("Please select a service type")
      if (typeof dynamicPrice !== "number") throw new Error("Live pricing unavailable. Please try again.")

      const resp = await submitService({ ...pendingPayload, pin })
      if (!resp.ok) {
        throw new Error(resp?.error || resp?.message || "Failed to process request")
      }

      setReferenceId(resp.reference || `WAEC-${Date.now()}`)
      setShowSuccess(true)
      toast({
        title: "Success!",
        description: `Your WAEC Pin(s) have been generated successfully${resp.reference ? ` with reference: ${resp.reference}` : ''}.`,
      })
    } catch (error: any) {
      const errorMessage = error?.message || error?.error || "Failed to process request. Please try again."
      toast({ title: "WAEC Pin Purchase Failed", description: errorMessage, variant: "destructive" })
    } finally {
      setIsSubmitting(false)
    }
  }

  const generatePDF = () => {
    const doc = new jsPDF()
    const finalQuantity = quantity === 0 ? Number.parseInt(customQuantity) || 1 : quantity

    doc.setFillColor(52, 87, 213)
    doc.rect(0, 0, 210, 40, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.text("UFriends Information Technology", 105, 20, { align: "center" })
    doc.setFontSize(14)
    doc.text("Education Pin Purchase Confirmation", 105, 30, { align: "center" })

    doc.setTextColor(0, 0, 0)
    doc.setFontSize(12)
    doc.text(`Service Type: ${serviceType}`, 20, 60)
    doc.text(`Candidate Name: ${candidateName || "N/A"}`, 20, 70)
    doc.text(`Quantity: ${finalQuantity}`, 20, 80)
    doc.text(`Price per Unit: ₦${servicePrice.toLocaleString()}`, 20, 90)
    doc.text(`Total Paid: ₦${totalPrice.toLocaleString()}`, 20, 100)
    doc.text(`Reference ID: ${referenceId}`, 20, 110)
    doc.text(`Date: ${new Date().toLocaleString()}`, 20, 120)

    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text("Generated by UFriends.com.ng — For Academic Use Only", 105, 280, { align: "center" })

    doc.save("WAEC_Pin_Receipt.pdf")
  }

  if (showSuccess) {
    return (
      <div className="min-h-screen bg-[#F9F7F3] p-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="max-w-2xl mx-auto"
        >
          <Card className="border-[#3457D5]">
            <CardHeader className="bg-[#3457D5] text-white">
              <CardTitle className="flex items-center gap-2">
                <GraduationCap className="h-6 w-6" />
                Purchase Successful!
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-4">
              <p className="text-lg">Your WAEC Pin(s) have been generated successfully.</p>
              <div className="bg-[#CCCCFF]/20 p-4 rounded-lg space-y-2">
                <p>
                  <strong>Reference ID:</strong> {referenceId}
                </p>
                <p>
                  <strong>Quantity:</strong> {quantity === 0 ? customQuantity : quantity}
                </p>
                <p>
                  <strong>Total Paid:</strong> ₦{totalPrice.toLocaleString()}
                </p>
              </div>
              <div className="flex gap-3">
                <Button onClick={generatePDF} className="bg-[#3457D5] hover:bg-[#2a46aa]">
                  <Download className="mr-2 h-4 w-4" />
                  Download Receipt
                </Button>
                <Button variant="outline" onClick={() => setShowSuccess(false)}>
                  Make Another Purchase
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#F9F7F3] p-6">
      <div className="max-w-6xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <h1 className="text-4xl font-bold text-[#3457D5] mb-2">WAEC Services</h1>
          <p className="text-gray-600">Purchase WAEC examination pins and scratch cards</p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-6">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <ShoppingCart className="h-5 w-5 text-[#3457D5]" />
                  Purchase WAEC Pin
                </CardTitle>
                <CardDescription>Select service type and quantity</CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="serviceType">Service Type</Label>
                    <Select value={serviceType} onValueChange={setServiceType} required>
                      <SelectTrigger>
                        <SelectValue placeholder="Select service type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="WAEC Pin">WAEC Pin / Scratch Card</SelectItem>
                        <SelectItem value="GCE Registration Pin">GCE Registration Pin</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="candidateName">Candidate Name (Optional)</Label>
                    <Input
                      id="candidateName"
                      value={candidateName}
                      onChange={(e) => setCandidateName(e.target.value)}
                      placeholder="Enter candidate name"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="quantity">Quantity</Label>
                    <Select value={quantity.toString()} onValueChange={(val) => setQuantity(Number.parseInt(val))}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1">1</SelectItem>
                        <SelectItem value="2">2</SelectItem>
                        <SelectItem value="3">3</SelectItem>
                        <SelectItem value="4">4</SelectItem>
                        <SelectItem value="5">5</SelectItem>
                        <SelectItem value="0">Custom</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {quantity === 0 && (
                    <div className="space-y-2">
                      <Label htmlFor="customQuantity">Custom Quantity</Label>
                      <Input
                        id="customQuantity"
                        type="number"
                        min="1"
                        value={customQuantity}
                        onChange={(e) => setCustomQuantity(e.target.value)}
                        placeholder="Enter quantity"
                        required
                      />
                    </div>
                  )}

                  {serviceType && (
                    <div className="bg-[#CCCCFF]/20 p-4 rounded-lg">
                      <p className="text-sm text-gray-700">
                        💰 Price per unit: ₦{servicePrice.toLocaleString()} — Total: ₦{totalPrice.toLocaleString()}
                      </p>
                    </div>
                  )}

                  <Button
                    type="submit"
                    disabled={isSubmitting || !serviceType}
                    className="w-full bg-[#3457D5] hover:bg-[#2a46aa]"
                  >
                    {isSubmitting ? "Processing..." : "Purchase Now"}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}>
            <Card className="bg-gradient-to-br from-[#3457D5]/10 to-[#CCCCFF]/20">
              <CardHeader>
                <CardTitle className="text-[#3457D5]">About WAEC Services</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-start gap-3">
                  <div className="bg-[#3457D5] text-white rounded-full w-8 h-8 flex items-center justify-center flex-shrink-0">
                    1
                  </div>
                  <div>
                    <h3 className="font-semibold mb-1">Instant Delivery</h3>
                    <p className="text-sm text-gray-600">Get your pins immediately after purchase</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="bg-[#3457D5] text-white rounded-full w-8 h-8 flex items-center justify-center flex-shrink-0">
                    2
                  </div>
                  <div>
                    <h3 className="font-semibold mb-1">Secure Payment</h3>
                    <p className="text-sm text-gray-600">All transactions are encrypted and secure</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="bg-[#3457D5] text-white rounded-full w-8 h-8 flex items-center justify-center flex-shrink-0">
                    3
                  </div>
                  <div>
                    <h3 className="font-semibold mb-1">24/7 Support</h3>
                    <p className="text-sm text-gray-600">Our team is always ready to assist you</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </div>
      <PinPrompt
        isOpen={isPinPromptOpen}
        onClose={() => setIsPinPromptOpen(false)}
        onConfirm={handlePinConfirm}
        isLoading={isSubmitting}
      />
    </div>
  )
}
