"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { FileText, AlertTriangle, Download } from "lucide-react"
import { PinPrompt } from "@/components/PinPrompt"
import { handleServiceError } from "@/lib/service-utils"
import { useToast } from "@/hooks/use-toast"
import jsPDF from "jspdf"
import { useDynamicPricing } from "@/hooks/useDynamicPricing"
import { formatPrice } from "@/lib/service-pricing"

export default function NINPrintoutPage() {
  const [showPrivacyWarning, setShowPrivacyWarning] = useState(true)
  const [nin, setNin] = useState("")
  const [isProcessing, setIsProcessing] = useState(false)
  const [isPinPromptOpen, setIsPinPromptOpen] = useState(false)
  const [pendingPayload, setPendingPayload] = useState<any>(null)
  const [data, setData] = useState<any>(null)
  const { toast } = useToast()

  // Dynamic pricing for NIN printout (no variant/params)
  const { price: servicePrice, isLoading: priceLoading, error: priceError, submitService } = useDynamicPricing(
    "nin",
    "printout",
    "default", // Changed from empty string to default or specific variant if needed
    {},
  )

  const handleSubmit = async () => {
    if (!nin || nin.length !== 11) {
      toast({ title: "Validation Error", description: "Enter a valid 11-digit NIN", variant: "destructive" })
      return
    }

    setPendingPayload({
      amount: servicePrice,
      idempotencyKey: crypto.randomUUID(),
      params: { nin },
      category: "nin",
      action: "printout"
    })
    setIsPinPromptOpen(true)
  }

  const handlePinConfirm = async (pin: string) => {
    setIsPinPromptOpen(false)
    setIsProcessing(true)
    try {
      const resp = await submitService({ ...pendingPayload, pin })

      if (!resp.ok) {
        handleServiceError(resp, toast, "Request Failed")
        return
      }

      setData(resp.data?.data || resp.data)

      toast({ title: "Success!", description: "NIN printout retrieved." })
    } catch (error: any) {
      const message = error?.message || error?.error || error?.detail || JSON.stringify(error)
      console.error("NIN Printout Error:", message)
      toast({ title: "Error", description: message, variant: "destructive" })
    } finally {
      setIsProcessing(false)
    }
  }

  const downloadPrintoutPDF = () => {
    try {
      const doc = new jsPDF()
      doc.setFontSize(18)
      doc.text("UFriends Information Technology", 70, 15)
      doc.setFontSize(14)
      doc.text("NIN Printout", 95, 25)
      doc.setFontSize(10)
      doc.text(`Date: ${new Date().toLocaleString()}`, 15, 40)
      doc.text(`NIN: ${nin}`, 15, 50)
      if (data?.full_name) doc.text(`Name: ${data.full_name}`, 15, 60)
      if (data?.date_of_birth) doc.text(`DOB: ${data.date_of_birth}`, 15, 70)
      doc.text("Note: This is a verification printout generated by UFriends.com.ng", 15, 250)
      doc.save(`nin-printout-${Date.now()}.pdf`)
      toast({ title: "Download Complete", description: "NIN printout PDF generated." })
    } catch (error: any) {
      console.error("PDF generation error:", error?.message || JSON.stringify(error))
      toast({ title: "Download Error", description: error?.message || "Failed to generate PDF.", variant: "destructive" })
    }
  }

  return (
    <div className="min-h-screen bg-[#F9F7F3] p-4 md:p-8">
      <Dialog open={showPrivacyWarning} onOpenChange={setShowPrivacyWarning}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full border-2 border-[#3457D5] bg-[#CCCCFF]/20">
              <AlertTriangle className="h-8 w-8 text-[#3457D5]" />
            </div>
            <DialogTitle className="text-center text-2xl font-bold">Privacy & Data Protection Warning</DialogTitle>
            <DialogDescription className="text-center text-sm leading-relaxed text-gray-600">
              By using this service, you confirm legal authority to process this data and accept liability for misuse.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-center">
            <Button onClick={() => setShowPrivacyWarning(false)} className="bg-[#3457D5] px-8 text-white hover:bg-[#3457D5]/90">
              I Understand & Accept
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <div className="mx-auto max-w-3xl">
        <Card className="border-[#CCCCFF]/30 shadow-lg">
          <CardHeader className="bg-gradient-to-r from-[#3457D5]/5 to-[#CCCCFF]/10">
            <CardTitle className="flex items-center text-[#3457D5]">
              <FileText className="mr-2 h-5 w-5" /> NIN Printout
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 pt-6">
            <div>
              <Label htmlFor="nin">NIN Number</Label>
              <Input id="nin" placeholder="Enter 11-digit NIN" maxLength={11} value={nin} onChange={(e) => setNin(e.target.value.replace(/\D/g, ""))} className="mt-2 border-[#CCCCFF] focus:border-[#3457D5]" />
            </div>
            {/* Dynamic Price Display */}
            <div className="bg-[#CCCCFF]/20 border border-[#CCCCFF]/50 rounded-lg p-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-[#2c3e50]">💰 Service Price:</span>
                <span className="text-2xl font-bold text-[#3457D5]">
                  {priceLoading ? "Loading..." : servicePrice == null ? "Not configured" : formatPrice(Number(servicePrice || 0))}
                </span>
              </div>
              {priceError && (
                <p className="mt-2 text-sm text-red-600">Failed to load price. You can still submit.</p>
              )}
            </div>
            <Button onClick={handleSubmit} disabled={isProcessing || nin.length !== 11 || priceLoading} className="w-full bg-[#3457D5] py-6 text-base font-semibold text-white hover:bg-[#3457D5]/90">
              {isProcessing ? "Processing..." : "Submit Request"}
            </Button>
            {data && (
              <Button onClick={downloadPrintoutPDF} className="w-full bg-green-600 py-6 text-base font-semibold text-white hover:bg-green-700">
                <Download className="mr-2 h-5 w-5" /> Download Printout (PDF)
              </Button>
            )}
          </CardContent>
        </Card>
      </div>
      <PinPrompt
        isOpen={isPinPromptOpen}
        onClose={() => setIsPinPromptOpen(false)}
        onConfirm={handlePinConfirm}
        isLoading={isProcessing}
      />
    </div>
  )
}
