var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/service-catalog/route.js")
R.c("server/chunks/node_modules_next_9e03b513._.js")
R.c("server/chunks/node_modules_@bufbuild_protobuf_dist_esm_469070b0._.js")
R.c("server/chunks/node_modules_@arcjet_protocol_04fd0396._.js")
R.c("server/chunks/a9bf9_@arcjet_analyze-wasm__virtual_arcjet_analyze_js_req_component_core_ff0d6734.js")
R.c("server/chunks/node_modules_@arcjet_analyze-wasm__virtual_d6f8b2ec._.js")
R.c("server/chunks/node_modules_@arcjet_analyze-wasm_07aad905._.js")
R.c("server/chunks/node_modules_@connectrpc_connect_dist_esm_61dd4314._.js")
R.c("server/chunks/node_modules_undici_d70e2fe1._.js")
R.c("server/chunks/node_modules_zod_7c2ff355._.js")
R.c("server/chunks/node_modules_entities_lib_e27fcc70._.js")
R.c("server/chunks/node_modules_f1c8b69f._.js")
R.c("server/chunks/[root-of-the-server]__6027db0b._.js")
R.c("server/chunks/_next-internal_server_app_api_service-catalog_route_actions_203409a8.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/service-catalog/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/service-catalog/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
