var R=require("./chunks/[turbopack]_runtime.js")("server/middleware.js")
R.c("server/chunks/node_modules_next_224ccd41._.js")
R.c("server/chunks/node_modules_51154d9a._.js")
R.c("server/chunks/node_modules_@bufbuild_protobuf_dist_esm_677a217c._.js")
R.c("server/chunks/node_modules_@arcjet_protocol_c00dfa3f._.js")
R.c("server/chunks/a9bf9_@arcjet_analyze-wasm__virtual_arcjet_analyze_js_req_component_core_2912558f.js")
R.c("server/chunks/node_modules_@arcjet_analyze-wasm__virtual_54c7d5a8._.js")
R.c("server/chunks/node_modules_@arcjet_analyze-wasm_0abc853f._.js")
R.c("server/chunks/node_modules_@connectrpc_connect_dist_esm_99008ba8._.js")
R.c("server/chunks/node_modules_undici_9a85e18f._.js")
R.c("server/chunks/node_modules_3b2c5a8f._.js")
R.c("server/chunks/[root-of-the-server]__b8af170f._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)").exports
